package leetCode.hash;

import java.util.Arrays;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */
public class Problem389 {

    /**
     * solution 1: use XOR to find the distinct element
     */
    public char findTheDifference1(String s, String t) {
    	int n = t.length();
    	char c = t.charAt(n - 1);
    	for (int i = 0; i < n - 1; ++i) {
    		c ^= s.charAt(i);
    		c ^= t.charAt(i);
    	}
    	return c;
    }

    /**
     * solution 2: use hashmap
     */
    public char findTheDifference2(String s, String t) {
        int[] chars = new int[26];
        Arrays.fill(chars, 0);
        for (char c : s.toCharArray()) {
            chars[c-'a'] ++;
        }
        for (char c : t.toCharArray()) {
            if (chars[c-'a'] == 0) {
                return c;
            }
            chars[c-'a'] --;
        }
        return 'a';
    }
}
