package leetCode.hash;

import java.util.Arrays;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */
public class Problem389 {

    public char findTheDifference(String s, String t) {
        int[] chars = new int[26];
        Arrays.fill(chars, 0);
        for (char c : s.toCharArray()) {
            chars[c-'a'] ++;
        }
        for (char c : t.toCharArray()) {
            if (chars[c-'a'] == 0) {
                return c;
            }
            chars[c-'a'] --;
        }
        return 'a';
    }
}
